/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Alert: typeof import('antd').Alert
  const Button: typeof import('antd').Button
  const Card: typeof import('antd').Card
  const Col: typeof import('antd').Col
  const ConfigProvider: typeof import('antd').ConfigProvider
  const DashboardOutlined: typeof import('@ant-design/icons').DashboardOutlined
  const Divider: typeof import('antd').Divider
  const Fragment: typeof import('react').Fragment
  const HomeOutlined: typeof import('@ant-design/icons').HomeOutlined
  const InfoCircleOutlined: typeof import('@ant-design/icons').InfoCircleOutlined
  const Layout: typeof import('antd').Layout
  const Link: typeof import('react-router').Link
  const Menu: typeof import('antd').Menu
  const Modal: typeof import('antd').Modal
  const Outlet: typeof import('react-router').Outlet
  const RocketOutlined: typeof import('@ant-design/icons').RocketOutlined
  const RouterProvider: typeof import('react-router').RouterProvider
  const Row: typeof import('antd').Row
  const SettingOutlined: typeof import('@ant-design/icons').SettingOutlined
  const Space: typeof import('antd').Space
  const Statistic: typeof import('antd').Statistic
  const Suspense: typeof import('react').Suspense
  const Tag: typeof import('antd').Tag
  const ThunderboltOutlined: typeof import('@ant-design/icons').ThunderboltOutlined
  const Typography: typeof import('antd').Typography
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const message: typeof import('antd').message
  const notification: typeof import('antd').notification
  const startTransition: typeof import('react').startTransition
  const theme: typeof import('antd').theme
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useHref: typeof import('react-router').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocation: typeof import('react-router').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router').useNavigate
  const useNavigationType: typeof import('react-router').useNavigationType
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router').useOutlet
  const useOutletContext: typeof import('react-router').useOutletContext
  const useParams: typeof import('react-router').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router').useResolvedPath
  const useRoutes: typeof import('react-router').useRoutes
  const useSearchParams: typeof import('react-router').useSearchParams
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
